FROM node:lts-alpine AS build-jemindraw
WORKDIR /app
COPY jemindraw/package*.json ./
RUN npm ci
COPY jemindraw/ .
RUN npm run build

FROM node:lts-alpine AS build-frontend
WORKDIR /app
COPY frontend/package*.json ./
RUN npm ci
COPY frontend/ .
RUN npm run build

FROM nginx:alpine
COPY --from=build-jemindraw /app/dist /usr/share/nginx/html/jemindraw
COPY --from=build-frontend  /app/dist /usr/share/nginx/html/frontend
COPY nginx/conf.d/sites.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
