FROM node:lts-alpine AS builder
WORKDIR /app
COPY jemindraw/package*.json ./
RUN npm ci
COPY jemindraw/ .
RUN npm run build

FROM nginx:alpine
COPY --from=builder /app/dist /usr/share/nginx/html
COPY nginx/conf.d/sites.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
